### ISSUE TITLE
Theme Builder

### ISSUE THREAD

**Issue by 3x1io** [queents/vilt#4]
## About

> Module Name `builder-module`

we need to build a module that has drag-and-drop components to use in the frontend apps with ready to use component build with vuejs

## Tasks

- [x] Build Builder Module
- [x] Build Builder Page
- [x] Build Builder Logic
- [x] Build Builder Lib
- [x] Build Builder vuejs page
- [x] Build Builder Drop & Drag
- [x] Build Builder Components
- [x] Make Builder Component Editable
- [ ] Make Builder Components Has Options
- [ ] Save Components To Database
- [ ] Load Components Input HTML
- [ ] Load Components Input a page and view it 
- [ ] Show Components On Last Preview
- [ ] Test and Deploy
